#!/bin/sh
# Generated by agent-ready — PreToolUse guard for destructive Bash commands.
# Exit 2 rejects the command and sends the reason back to the agent.
input=$(cat)
deny() {
  echo "agent-ready guard blocked this command: $1" >&2
  exit 2
}
case "$input" in
  *--force-with-lease*) ;;
  *'git push'*--force* | *'git push'*' -f '* | *'git push'*' -f"'*)
    deny 'force push rewrites remote history. Use --force-with-lease and confirm with the user first.' ;;
esac
case "$input" in
  *'rm -rf'* | *'rm -fr'*)
    case "$input" in
      *'rm -rf /"'* | *'rm -rf / '* | *'rm -rf /*'* | *'rm -fr /"'* | *'rm -fr / '* | \
      *'rm -rf ~'* | *'rm -fr ~'* | *'rm -rf'*'$HOME'* | *'rm -fr'*'$HOME'*)
        deny 'recursive delete of a root or home directory.' ;;
    esac ;;
esac
exit 0
