#!/bin/sh
# Generated by agent-ready — SessionStart hook.
# Surfaces drift between the repository and its generated agent docs, so the
# session starts with the self-maintenance rule already triggered.
cd "${CLAUDE_PROJECT_DIR:-.}" || exit 0
command -v agent-ready >/dev/null 2>&1 || exit 0
out=$(agent-ready check 2>&1)
if [ $? -ne 0 ]; then
  echo 'agent-ready check found drift between the repository and its agent docs:'
  echo "$out"
  echo 'Run `agent-ready update` to repair it (see the self-maintenance rules in CLAUDE.md).'
fi
exit 0
